Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryBook.Areas.Data;
using LibraryBook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;

namespace LibraryBook.Controllers
{
    [Authorize(Roles = "SystemAdministrator")]
    public class LanguagesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LanguagesController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Languages
        public async Task<IActionResult> Index()
        {
            return _context.Languages != null ?
                        View(await _context.Languages.ToListAsync()) :
                        Problem("Entity set 'MyDbContext.Language'  is null.");
        }


        // GET: Languages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Languages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,IsSystemLanguage,IsAvailable")] Language language)
        {
            if (ModelState.IsValid)
            {
                _context.Add(language);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(language);
        }

        // GET: Languages/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Languages == null)
            {
                return NotFound();
            }

            var language = await _context.Languages.FindAsync(id);
            if (language == null)
            {
                return NotFound();
            }
            return View(language);
        }

        // POST: Languages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,IsSystemLanguage,IsAvailable")] Language language)
        {
            if (id != language.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(language);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LanguageExists(language.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(language);
        }

        // GET: Languages/Delete/5
        private bool LanguageExists(string id)
        {
            return (_context.Languages?.Any(e => e.Id == id)).GetValueOrDefault();
        }


        [AllowAnonymous]
        public IActionResult ChangeLanguage(string id, string returnUrl)
        {
            string culture = Thread.CurrentThread.CurrentCulture.ToString();
            try
            {
                culture = id + culture.Substring(2, 3);
            }
            catch
            {
                culture = id + "-BE";
            }

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
                );


            return LocalRedirect(returnUrl);
        }
    }
}

Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryBook.Models;
using Microsoft.AspNetCore.Authorization;
using LibraryBook.Areas.Data;
using Microsoft.AspNetCore.Identity;

namespace LibraryBook.Controllers
{
    
    public class LoansController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<LibraryUser> _userManager;

        public LoansController(ApplicationDbContext context, UserManager<LibraryUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        // GET: Loans
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string titleFilter, int selectedGroup)
        {
            var libraryBookContext = _context.Loans
                .Include(l => l.Book)
                .Include(l => l.Loaner); // Include the Loaner (LibraryUser)

            return View(await libraryBookContext.ToListAsync());
        }


        // GET: Loans/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loans
                .Include(l => l.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }

        // GET: Loans/Create
        [Authorize(Policy = "CreateLoanPolicy")]
        public IActionResult Create()
        {
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Title");
            return View();
        }

        // POST: Loans/Create
        [Authorize(Policy = "CreateLoanPolicy")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LoanDate,ReturnDate,Deleted,BookId")] Loan loan)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(User);
                loan.LoanerId = user?.Id;
                loan.UserId = user?.Id;

                // Set IsLoaned status of the book to true
                var book = await _context.Books.FindAsync(loan.BookId);
                if (book != null)
                {
                    book.IsLoaned = true;
                    book.Loaner = user;
                    _context.Update(book);
                }
                _context.Add(loan);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Books");
            }

            foreach (var modelState in ViewData.ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine($"ModelState Error: {error.ErrorMessage}");
                }
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Author", loan.BookId);
            return View(loan);
        }

        // GET: Loans/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loans.FindAsync(id);
            if (loan == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Author", loan.BookId);
            return View(loan);
        }

        // POST: Loans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("Id,LoanDate,ReturnDate,Deleted,BookId")] Loan loan)
        {
            if (id != loan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoanExists(loan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Author", loan.BookId);
            return View(loan);
        }

        // GET: Loans/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loan = await _context.Loans
                .Include(l => l.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loan == null)
            {
                return NotFound();
            }

            return View(loan);
        }

        // POST: Loans/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var loan = await _context.Loans.FindAsync(id);

            if (loan != null)
            {
                var bookId = loan.BookId;
                var book = await _context.Books.FindAsync(bookId);

                if (book != null)
                {
                    // Reset book properties
                    book.IsLoaned = false;
                    book.LibraryUserId = null;
                }

                _context.Loans.Remove(loan);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool LoanExists(int? id)
        {
            return _context.Loans.Any(e => e.Id == id);
        }
    }
}

Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LibraryBook.Areas.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Linq;

namespace LibraryBook.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<LibraryUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(ApplicationDbContext context, UserManager<LibraryUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Users
        public async Task<IActionResult> Index(string roleFilter)
        {
            // Retrieve the Users table from HttpContext.Items using middleware
            var usersTable = HttpContext.Items["UsersTable"] as IQueryable<LibraryUser>;

            // Default to all users if usersTable is null (in case middleware is not working)
            var users = usersTable ?? _context.Users.AsQueryable();

            // Populate roles for the filter dropdown
            ViewBag.Roles = await _roleManager.Roles.Select(r => r.Name).ToListAsync();

            // Set the current filter in ViewBag to maintain the selected role in the view
            ViewBag.CurrentFilter = roleFilter;

            // Filter by role if a role is selected
            if (!string.IsNullOrEmpty(roleFilter))
            {
                var roleIds = await _roleManager.Roles
                    .Where(r => r.Name == roleFilter)
                    .Select(r => r.Id)
                    .ToListAsync();

                var userIdsInRole = await _context.UserRoles
                    .Where(ur => roleIds.Contains(ur.RoleId))
                    .Select(ur => ur.UserId)
                    .ToListAsync();

                users = users.Where(u => userIdsInRole.Contains(u.Id));
            }

            return View(await users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,UserName,Email")] LibraryUser user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,FirstName,LastName,UserName,Password,Email")] LibraryUser user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer _localizer

@{
    // ophalen taal van de gebruiker
    string languageId = "nl";
    string cookieCulture = Context.Request.Cookies[CookieRequestCultureProvider.DefaultCookieName];
    if (cookieCulture != null)
    {
        languageId = cookieCulture.Substring(2, 2);
    }
    string LanguageName = Language.LanguagesById[languageId].Name;

    // ophalen huidige pagina
    var thisPage = string.IsNullOrEmpty(Context.Request.Path) ? "~/index.html" : $"~{Context.Request.Path.Value}";
}

<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown" data-bs-toggle="dropdown">@_localizer["Talen"]</a>
        <ul class="dropdown-menu">
            @foreach (Language language in Language.Languages)
                if (language.Id != languageId && language.IsSystemLanguage)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area=""
                           asp-controller="Languages"
                           asp-action="ChangeLanguage"
                           asp-route-id="@language.Id"
                           asp-route-returnUrl="@thisPage">
                            @language.Name
                        </a>
                    </li>
                }
        </ul>
    </li>
</ul>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryBook.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LibraryBook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@_localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@_localizer["Privacy"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">@_localizer["Books"]</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">@_localizer["Users"]</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                           {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Loans" asp-action="Index">@_localizer["Loans"]</a>
                                </li>
                            }
                        }


                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_LanguagePartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LibraryBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">@_localizer["Confidentialiteit"]</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>